files: ^backend/
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        name: Ensure that code don't have trailing whitespace
      - id: check-ast
        name: Check python abstract syntax trees
      - id: check-case-conflict
        name: Check for case conflicts
      - id: check-json
        name: Check JSON files format
      - id: check-merge-conflict
        name: Check for merge conflicts in code
      - id: end-of-file-fixer
        name: Files should end with empty line
        exclude: ".json"
      - id: end-of-file-fixer
        name: Newline at end of file
      - id: name-tests-test
        name: Tests should begin with test_
        args: ["--django"]
        exclude: "^(?!helpers/)"
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        args: [--line-length=150]
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        args: [--max-line-length=150]
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black"]
